from pages.About_Us import about_page
from pages.About_Us import tutorials_page
from pages.About_Us import glossary_page
from pages.Home_Page import home_page
from pages.About_Us import meta_data_page
from pages.Search import search_page
from pages.About_Us import citations_page
from pages.Login import login_page
from pages.individual import gene_info_page
from pages.individual import mirna_info_page
from pages.individual import rna_type_page
from pages.individual import spatial_info_page
from pages.individual import ppi_info_page
from pages.individual import go_info_page
from pages.individual import local_info_page
from pages.individual import orthologs_info_page
from pages.individual import snp_info_page
